print("")
print("")
print("                                                  WELCOME TO MY PROGRAM")
print("")
print("")
print("                                           ========== HIKMATUL SHOIMAH  ==========")
print("                                           =========  10 NOVEMBER 2020   =========")
print("")
print("")
print("                                ***          ***     **********         **********       ")
print("                                ***          ***     ************       ************       ")
print("                                ***          ***     ***       ****     ***     *****  ")
print("                                ***          ***     ***        ****    ***      *****  ")
print("                                ***          ***     ***       ****     ***       *****       ")
print("                                ****************     *************      ***        ****** ")
print("                                ****************     *************      ***        ****** ")
print("                                ***          ***     ***        ****    ***       ******          ")
print("                                ***          ***     ***        ****    ***      ******   ")
print("                                ***          ***     ***       ****     ***     ******  ")
print("                                ***          ***     *************      *************      ")
print("                                ***          ***     ************       ************      ")
print("")
print("                                      ========== BARAKALLAH FII UMRIK ==========        ")
print("                                      ========== SUKSES TERUS DEGCANS ==========       ")
print("                               ========== TETAPLAH MENJADI WANITA YANG KUAT ==========   ")
print("")
print("")
print("")
print("")
print("")